### PR TITLE
ENH: SVD-based regularization

### PR DESCRIPTION
**Pull request by Eric89GXL**
cc @staulu @mdclarke this has `'svd'` movecomp for raw and Evoked

### CODE REVIEW

**Comment by mdclarke** [comment]
Hi Eric

Is there a function available to Samu and I to use the SVD movement 
compensation? Or is it a parameter added to an existing function?

Thanks
Maggie

**Comment by Eric89GXL** [comment]
`regularize='svd'` is a new option for `average_movements` and `maxwell_filter`.

FYI in PRs you can look at the lines changed by clicking on the `Files changed` tab at the top, which would take you here for this PR:

https://github.com/Eric89GXL/mne-python/pull/23/files

From there you can try to infer the answers to questions like that if you're feeling adventurous. If I've done my job properly, usually the appropriate change will be documented properly, like in these two places:

https://github.com/Eric89GXL/mne-python/pull/23/files#diff-039672dd43aed72bef3343aff2aef3b1R2707
https://github.com/Eric89GXL/mne-python/pull/23/files#diff-39dd3839136bed63061a3c7ac20540b3R101

**Comment by Eric89GXL** [comment]
(Reading and reviewing other people's code is a skill all of its own, so it might be worth learning depending on what you want to do)

**Comment by mdclarke** [comment]
Thanks Eric! I will definitely practice this

-Maggie

**Pull request closed without merging**
